[package]
name = "generate-endpoints"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true, features = ["json", "stream", "multipart"] }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
percent-encoding = "2.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
