[package]
name = "fal"
version = "0.1.0"
edition = "2021"

[dependencies]
fal-derive = { path = "../fal-derive" }
base64 = "0.22"
image = "0.25"
reqwest = { version = "0.12", features = ["json", "stream", "multipart"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
itertools = "0.13"
thiserror = "1"
futures = "0.3"
strum = { version = "0.26", features = ["derive"] }
rand = "0.8"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }