name: Generate Endpoints

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  generate:
    name: Generate Endpoints
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Generate endpoints
        run: cargo run -p generate-endpoints

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create branch
        if: steps.git-check.outputs.changes == 'true'
        run: |
          branch_name="update/endpoints-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $branch_name
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "chore: update generated endpoints"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "chore: update generated endpoints"
          body: |
            This PR was automatically created by the Generate Endpoints workflow.

            - Updates generated endpoints
          branch: ${{ env.BRANCH_NAME }}
          base: main
